# Generated by Django 4.2.2 on 2024-02-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default='', max_length=20)),
                ('Email', models.CharField(default='', max_length=40)),
                ('Password', models.CharField(default='', max_length=40)),
                ('Confirmpassword', models.CharField(default='', max_length=40)),
            ],
        ),
    ]
